name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract dist
      run: tar xvf tools/rpcf-0.1.0.tar.gz
    - name: make
      run: cd rpcf-0.1.0;./configure;make;make check;make distcheck
