name: C++ CI with GmSSL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: checkout gmssl
      uses: actions/checkout@v3
      with:
          repository: zhiming99/GmSSL
          path: ./gmssl
        
    - name: update repository
      run: sudo apt-get -o Acquire::Retries=3 update
    - name: install tzdata
      run: sudo DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
    - name: install tools
      run: sudo apt-get -o Acquire::Retries=3 install -y gcc g++ python3 python3-dev python3-pip flex bison libtool shtool automake autoconf autotools-dev make dbus libdbus-1-3 libdbus-1-dev libkrb5-3 libkrb5-dev liblz4-1 liblz4-dev lz4 openssl libssl3 libssl-dev libcppunit-1.15-0 libcppunit-dev bash net-tools procps swig ccache cmake;pip3 install numpy wheel
    - name: install sip
      run: sudo apt-get -y install sip5-tools || sudo apt-get -y install sip-dev python3-sip python3-sip-dev || true; sudo apt-get -y install fuse3 libfuse3-3 libfuse3-dev || true; sudo apt-get -y install libjsoncpp1 libjsoncpp-dev || sudo apt-get -y install libjsoncpp25 libjsoncpp-dev 

    - name: build gmssl
      run: cd ./gmssl/;mkdir build;cd build;cmake ..;make;sudo make install
    - name: ls files
      run: echo ls ./gmssl/build/bin/libgmssl.a;ls ./gmssl/build/bin/libgmssl.a -l || echo no such file;echo ls /usr/local/lib/libgmssl.a;ls /usr/local/lib/libgmssl.a || echo no such file
